You can create a tensor from NumPy array, and vice versa.
You can even apply TensorFlow operations to NumPy arrays and NumPy operations to tensors:

In [3]:
import tensorflow as tf
import numpy as np

a = np.array([2., 4., 5.])

tensor1 = tf.constant(a)

print(tensor1)

tensor2 = tensor1.numpy()

print(tensor2)

tensor3 = tf.square(a)

print(tensor3)

tf.Tensor([2. 4. 5.], shape=(3,), dtype=float64)
[2. 4. 5.]
tf.Tensor([ 4. 16. 25.], shape=(3,), dtype=float64)
