You can create a tensor from NumPy array, and vice versa.
You can even apply TensorFlow operations to NumPy arrays and NumPy operations to tensors:

In [3]:
import tensorflow as tf
import numpy as np

a = np.array([2., 4., 5.])

tensor1 = tf.constant(a)

print(tensor1)

tensor2 = tensor1.numpy()

print(tensor2)

tensor3 = tf.square(a)

print(tensor3)

tf.Tensor([2. 4. 5.], shape=(3,), dtype=float64)
[2. 4. 5.]
tf.Tensor([ 4. 16. 25.], shape=(3,), dtype=float64)


NumPy uses 64-bit precision by default, while TensorFlow uses 32-bit using less RAM.
So when you create a tensor from a NumPy array, make sure to set dtype=tf.float32

In [4]:
array1 = np.array([1., 2., 3., 4., 5., 6.])

tensor = tf.constant(array1, dtype=tf.float32)

print(tensor)

print(tensor.numpy())


tf.Tensor([1. 2. 3. 4. 5. 6.], shape=(6,), dtype=float32)
[1. 2. 3. 4. 5. 6.]
